FROM base-srt:v2
EXPOSE 1234/udp
ENV REPORT_FREQUENCY=1000ms
ENV LATENCY=100
ENV ID="receiver"
RUN echo "'Report frequency set to $REPORT_FREQUENCY milliseconds'"
RUN mkdir /logs
COPY entrypoint_rcv.sh /
CMD ["/entrypoint_rcv.sh"]
