apiVersion: v1
kind: Service
metadata:
  name: {{ include "deep-srt-receiver.fullname" . }}
  labels:
{{ include "deep-srt-receiver.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: srt-input
      protocol: UDP
      name: srt-input
  selector:
    app.kubernetes.io/name: {{ include "deep-srt-receiver.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
