apiVersion: v1
kind: Service
metadata:
    name: receiver
spec:
    type: ExternalName
    externalName: {{ .Values.receiverService.name }}
    ports:
      - port: {{ .Values.receiverService.port }}
        protocol: UDP
        name: srt
